### ISSUE TITLE
Major deobfuscation issue

### ISSUE THREAD

**Issue by Taguar258** [kkar/PyFuscator#1]
Edit the obfuscated source code and replace the exec with print.
And you are going to print out the source code.

**Comment by analyserdmz** [comment]
> Edit the obfuscated source code and replace the exec with print.
> And you are going to print out the source code.

The point is to avoid string based detections. Not hide the source code from reversing.

**Comment by Taguar258** [comment]
@analyserdmz What do you use this for?
